name: Deploy Games

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build -Doptimize=ReleaseSmall
      - name: Build Games
        shell: bash
        run: |
          mv zig-out/bin/*.wasm .

          echo "ASSET1=snake.wasm" >> $GITHUB_ENV
          echo "ASSET2=pong.wasm" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            ${{ env.ASSET1 }}
            ${{ env.ASSET2 }}
